import { createApp } from 'vue'
// import App from './01_setup函数的体验/App.vue'
// import App from './02_setup定义数据/App.vue'
// import App from './02_setup定义数据/App2.vue'
// import App from './03_setup其他函数/App.vue'
// import App from './04_setup中的toRefs/App.vue'
// import App from './05_setup中computed/App.vue'
// import App from './06_setup中ref 引用元素/App.vue'
// import App from './07_setup生命周期函数/App.vue'
// import App from './08_setup的Provide和inject/App'
// import App from './09_setup侦听数据变化/App-watch.vue'
// import App from './09_setup侦听数据变化/App-watchEffect.vue'
// import App from './10_setup-Hooks练习/App.vue'
import App from './11_script- setup语法/App.vue'

createApp(App).mount('#app')
